# -*- coding: utf-8 -*-
"""Python Tutorial - Intro to AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNg9HJA9UC_j3Ga3ksVuzAHts9QZfPBC

# **Intro:**

預設同學都已學過基本程式設計，正式課程開始前的助教課目的是讓不熟悉 python 語法的同學盡快進入狀況。
python 的工具、套件相當多元，鼓勵同學作業、研究需要時多多利用網路上的資源。

*   助教課目的、作業、考試
*   簡介 Colab
*   資料容器
*   流程控制
*   stack & queue
*   Random Generator
*   自訂函數
*   常用套件 numpy, pandas
*   (可視化常用工具 matplotlib, 機器學習常用工具 scikit-learn)

---

# **List**

List 類似於 C/C++ 中的陣列，然而不同的是 list 會自動動態調整其大小(容量)，且能儲存混合型態的資料。

Python List Methods: index(), append(), extend(), insert(), remove(), count(), pop(), reversa(), sort(), copy(), clear()...
"""

# Simply use [] to initialize a list.
# It can hold data of mixed types.
a_list = [-2, 666, 3.14, "Hello"]
print(a_list)

# The list object will automatically adjust its size to contain new data.
# The `append` method add its argument to the end of the list.
a_list.append("world")
print(a_list)

# The insert() method inserts an element to the list at the specified index.
# list.insert(index, element)
a_list.insert(4, 'lovely')
print(a_list)

# The remove() method removes the first matching element (which is passed as an argument) from the list.
# list.remove(element)
a_list.remove(3.14)
print(a_list)

# The pop() method removes the item at the given index from the list and returns the removed item.
# list.pop(index)
a_list.pop(2)
print(a_list)

# Assigning a list to another variable copies only its referece.
b_list = a_list
b_list[0] = 100
print("a_list =", a_list)
print("b_list =", b_list)

# You can call the `copy()` method to duplicate a list.
b_list = a_list.copy()
b_list[0] = 0
print("a_list =", a_list)
print("b_list =", b_list)

# You get a slice of a list using index range. The syntax goes as `a_list[begin, end]`.
# The `begin` index is included, while the `end` inde  x is excluded.
print("a_list[1:3] =", a_list[1:3])

# You can add a list to another simply with the `+` operator.
print("a_list + b_list[0:2] =", a_list + b_list[0:2])

"""重要觀念：list 僅儲存內容物之參考 (reference)，而非物件實例 (instance)。"""

# It's important to know that a list holds only the reference of each item.
# If you need a copy of data instead of just reference, call the `copy()` method.
print("** Without making a copy, the original item will be affected. **")
c_list = [1, 2, 3]
d_list = ['a', 'b', 'c']
e_list = [c_list, d_list]
print("c_list =", c_list)
print("d_list =", d_list)
print("e_list =", e_list)

e_list[0][0] = -1
print("(after changing `e_list`)")
print("c_list =", c_list)
print("d_list =", d_list)
print("e_list =", e_list)

print("** With making a copy, the original item won't be changed. **")
c_list = [1, 2, 3]
d_list = ['a', 'b', 'c']
e_list = [c_list.copy(), d_list.copy()]
print("c_list =", c_list)
print("d_list =", d_list)
print("e_list =", e_list)

e_list[0][0] = -1
print("(after changing `e_list`)")
print("c_list =", c_list)
print("d_list =", d_list)
print("e_list =", e_list)

"""## **用 sort() 或 sorted() 來排序項目**
* 串列方法 sort() 可**就地**排序串列本身。
* 通用函式 sorted() 可回傳排序後的串列**副本**。
"""

marxes = ['Groucho', 'Chico', 'Harpo']
sorted_marxes = sorted(marxes)
print("sorted_marxes: ", sorted_marxes)
print("marxes: ", marxes)
print("----")

marxes.sort()
print("After marxes.sort()")
print("marxes: ", marxes)

numbers = [2, 1, 4.0, 3]
numbers.sort()
print(numbers)
numbers.sort(reverse=True)
print(numbers)

"""# **tuple**

tuple 是類似於 list 的循序式資料容器，然而 tuple 在初始化後即不能再改變 (immutable)。適合用於儲存非變動長度的資料組。
"""

a_tuple = (1, 2, 3)
b_tuple = a_tuple + (4, 5)

print("a_tuple =", a_tuple)
print("b_tuple =", b_tuple)

"""# **dict**

dict 可視為 list 的擴充，不僅能以整數作為索引 (index)，還能以字串 (string) 等不可變的 (immutable) 資料型態作為索引。適合用於儲存非序列式存取的資料組。
"""

a_dict = {
    "name": "John",
    "age": 20,
    "job": "engineer",
}
print("a_dict =", a_dict)
print("a_dict['age'] =", a_dict['age'])
print("----")

# You can create new key-value pair with simple assignment.
a_dict["is_adult"] = True
print("a_dict =", a_dict)

"""# **set**

set 類似於 list，然而 set 不會重複儲存資料，可確保其內容物的唯一性。適合儲存時常需要檢查重複性的資料組。
"""

a_set = set([1, 2, 3, 4, 5])
b_set = set([3, 4, 5, 'a', 'b', 'c'])

# check whether something is in a set
print("Is 'a' in a_set?", 'a' in a_set)
print("Is 'a' in b_set?", 'a' in b_set)
print("----")

# union of sets, i.e., the items in `a_set` or `b_set`
print("union: ", a_set.union(b_set))

# intersection of sets, i.e., the items in both `a_set` and `b_set`
print("intersection: ", a_set.intersection(b_set))

# difference of sets, i.e., the items in `a_set` not in `b_set`
print("difference: ", a_set.difference(b_set))

"""# **if, elif, else 條件判斷**
* if, elif, else 都是 Python 的陳述式，它們的功能是檢查一個條件。
* 注意縮排的使用。
* 透過運算子來測試相等性，並回傳 True 或 False。

```
if condition:
    statement1 for True condition
else:
    statement2 for False condition
```


---

```
if condition 1:
    statement1 for True Condition1
elif condition2:
    statement 2 for True Condition2
elif condition3:
    statement 3 for True Condition3
else:
    statements for Each Condition False
```
"""

a = 4
if a == 3:
	print('a is 3')
else:
	print('a is not 3')

print("----")

a = 1
b = 2
if a > b:
	print('a is greater')
elif a == b:
	print('a is equal to b')
else:
	print('b is greater')

"""用 in 來做多項比較"""

letter = 'o'
vowel_set = {'a', 'e', 'i', 'o', 'u'}
letter in vowel_set

vowel_list = ['a', 'e', 'i', 'o', 'u']
letter in vowel_list

vowel_tuple = ('a', 'e', 'i', 'o', 'u')
letter in vowel_tuple

vowel_string = "aeiou"
letter in vowel_string

"""# **for loops**

```
for i in sequence:
  statements
```


"""

for x in range(0, 3):
  print(x)

theBeatles = ['John Lennon', 'Paul McCartney', 'Ringo Starr', 'George Harrison']
for i in range(len(theBeatles)):
  print(theBeatles[i])
print("----")

instrument = {'John Lennon': 'vocals', 'Paul McCartney': 'bass', 'Ringo Starr': 'drum', 'George Harrison': 'guitars'}
for i, j in instrument.items():
  print(i, j)
print("----")

"""# **while loops**

```
while test_expression:
  body of while
```
"""

count = 0
while (count < 9):
   print('The count is:', count)
   count += 1

"""# **Nested loops**
Nested loops are useful when for each pass through the outer loop, you need to repeat some action on the data in the outer loop.

Ex. handle multi-dimensional cases...
"""

# outer loop
# to iterate from 1 to 5
for i in range(1, 6):
  # inner loop
  for j in range(1, 6):
    # print multiplication
    print(i * j, end=' ')
  print()

my_watch = ['Rolex', 'Omega', 'Patek Philippe', 'Richard Mille']
# outer loop
for watch in my_watch:
  # inner while loop
  count = 0
  while count < 5:
    print(watch, end=' ')
    # increment counter
    count+=1
  print()

"""# **break & continue**


*   break: 中斷執行中的迴圈，並跳出該迴圈，繼續執行迴圈後的程式。
*   continue: 跳過 continue 後的敘述，直接進入下一次迴圈。

```
for i in sequence:
  # statements inside for-loop
  if condition:
    break
  # statements inside for-loop

# statements outside for-loop <= break to here
```


```
for i in sequence:
  # statements inside for-loop <= continue to here
  if condition:
    continue
  # statements inside for-loop

# statements outside for-loop
```
"""

count=0
for string in 'hello':
  count+=1
  if string == 'l':
      break
  print(string)
print('count:', count) # <= break to here
print("----")

count=0
for string in 'hello':
  count+=1        # <= continue to here
  if string == 'l':
      continue
  print(string)
print('count:', count)

"""# **enumerate**
enumerate() 函式可返回一個列舉型別的物件，並新增一個計數器變數來迭代一個列表或其他型別的集合。
```
enumerate(iterable, start_index)
```
"""

# enumerate in list
my_garage = ['BMW', 'Benz', 'Maserati', 'Porche']
for _, car in enumerate(my_garage):
  print(_, car)

"""## Iterate through a dictionary."""

# enumerate in dict
d1 = {'a' : 15,'b' : 18,'c' : 20}

for i,j in enumerate(d1):
    print(i,j)

for i, (j,k) in enumerate(d1.items()):
    print(i,j,k)

for i,j in enumerate(d1.keys()):
    print(i,j)

for i,j in enumerate(d1.values()):
    print(i,j)

"""# **Queue & Stack**
Queue 和 stack 都是循序存取式資料結構，然而他們對存入與取出資料的順序不同。

Queue 遵守 first in first out (FIFO) 原則
+ 存入資料(insert)：放到序列的最前端
+ 取出資料(pop)：取出序列中最末端的資料

Stack 遵守 first in last out (FILO) 原則
+ 存入資料(append)：放到序列的最末端
+ 取出資料(pop)：取出序列中最末端的資料

"""

#### Queue (implemented with `list`) ####
vowel_queue = []
print(vowel_queue)
vowel_queue.insert(0, 'a')
print(vowel_queue)
vowel_queue.insert(0, 'e')
print(vowel_queue)
vowel_queue.insert(0, 'i')
print(vowel_queue)
vowel_queue.insert(0, 'o')
print(vowel_queue)
vowel_queue.insert(0, 'u')
print(vowel_queue)
print("--")

while len(vowel_queue) > 0:
  print(vowel_queue.pop(), "/", vowel_queue)

print("----")

# Please note that implementing queue with list is not optimial for performance.
# If you need high performance implementation, please refer to `collections.deque` https://docs.python.org/zh-tw/3/library/collections.html#collections.deque.

#### Stack (implemented with `list`) ####
vowel_stack = []
print(vowel_stack)
vowel_stack.append('a')
print(vowel_stack)
vowel_stack.append('e')
print(vowel_stack)
vowel_stack.append('i')
print(vowel_stack)
vowel_stack.append('o')
print(vowel_stack)
vowel_stack.append('u')
print(vowel_stack)
print("--")

while len(vowel_stack) > 0:
  print(vowel_stack.pop(), "/", vowel_stack)

print("----")

"""# **Random Generator**

以下程式碼片段示範
+ 隨機產生指定範圍內之整數
+ 隨機產生指定範圍內之實數
+ 隨機產生排列組合
"""

import random

n  = 20
lb = 0
ub = 99

# Randomly generate n integers within {lb, lb+1, ..., ub}
randlist = [random.randint(lb, ub) for i in range(n)]
print("(1)", randlist)

# Randomly generate n real values in [0.0, 1.0)
randlist = [random.random() for i in range(n)]
print("(2)", end=" ")
for value in randlist:
  print("%.2f" % value, end=", ")
print()

# Randomly generate n real values in [lb, ub]
randlist = [random.uniform(lb, ub) for i in range(n)]
print("(3)", end=" ")
for value in randlist:
  print("%.2f" % value, end=", ")

# Randomly shuffle a list
lb, ub = 1, 20
i_list = list(range(lb, ub))
print("Before shuffle =", i_list)
random.shuffle(i_list)
print("After shuffle  =", i_list)
i_list.sort()
print("Sort back      =", i_list)

# Randomly draw k items from a list "without replacement": 1) shuffle, 2) slice
k = 5
i_list = list(range(lb, ub))
print("Population    =", i_list)
random.shuffle(i_list)
print("After shuffle =", i_list)
i_list = i_list[0:k]
print("After slicing =", i_list)

# Randomly draw k items from a list "with replacement"
k = 5
i_list = list(range(lb, ub))
print("Population =", i_list)
samples = random.choices(i_list, k=k)
print("Samples    =", samples)

"""# **Function**
programming 概念：DRY (Don't Repeat Yourself)

適當地進行封裝，達到程式碼的 reusable。建構函示 (function) 即可提高維護性及可讀性，並達到 reusable。

### **用 def 定義函式，用小括號呼叫函式**
"""

def make_a_sound():
  print('quack')

make_a_sound()

"""### **引數 Argument & 參數 Parameter**
From stack overflow:

* An argument is an expression used when calling the method.
* A parameter is the variable which is part of the method’s signature (method declaration).
* 引數 (Argument) 是用於呼叫函式，
* 參數 (Parameter) 是方法簽章 (方法的宣告)。

```
void Foo(int i, float f)
{
    // Do things
}

void Bar()
{
    int num = 1;
    Foo(anInt, 2.0);
}
```

num 與 2.0 即為 引數 (Argument)，或稱為 函式引數 (Argument of a Function)。
i 與 f 則為 參數 (Parameter)。

### **位置性引數 Positional Arguement**
位置性引數(Positional Arguement)為最常見的引數類型，他們的值會被依序複製到對應的參數。
"""

def menu(wine, entree, dessert):
  return {'wine': wine, 'entree': entree, 'dessert': dessert}

menu('Balvenie', 'chicken', 'cake')

"""### **關鍵字引數 Keyword Arguement**
提高可讀性，避免位置引數的混亂。可以用引數對應的參數名稱來指定引數，即使指定順序與函式定義的順序不同也沒問題。

特別注意：同時使用位置與關鍵字引數時來呼叫函式時，必須將位置引數放在前面。



"""

menu(entree='beef', dessert='bagel', wine='bordeaux')

"""### **預設參數值 Default Arguement**

必要引數(Required Arguement)必須放在預設引數(Optional Arguement)的前面。
"""

def menu(wine, entree, dessert='pudding'):
  return {'wine': wine, 'entree': entree, 'dessert': dessert}

menu('chardonnay', 'chicken')

"""### ***args,** ****kwargs運算子**
在函式參數裡的 * 可以將不固定數量的位置引數打包成 tuple 的資料型態。
"""

def print_args(*args):
  print('Positional tuple: ', args)

print_args()

print_args(3, 8, 4, 'Hi!', "Let's goooo")

"""如果你的函式也需要位置引數，則位置引數需要放在前面，*args放在最後，使它可以抓取所有其餘引數。"""

def print_more(required1, required2, *args):
  print('Need this one: ', required1)
  print('Need this one too: ', required2)
  print('All the rest: ', args)

print_more('cap', 'gloves', 'scarf', 'monocle', 'mustache wax')

"""你也可以使用 ** 來將關鍵字引數 (Keyword Argument) 組成字典 dictionary，其中關鍵字參數的鍵 (Key) 對應到字典 (Dictionary) 的鍵 (Key)，指派的值 (Value) 對應到字典 (Dictionary) 的值 (Value)。"""

def classroom(**kwargs):
  for key, value in kwargs.items():
    print ("%s == %s" %(key, value))

classroom(first ='Introduction', mid ='to', last='AI')

def classroom(arg1, **kwargs):
  print(arg1)
  for key, value in kwargs.items():
    print ("%s == %s" %(key, value))

classroom('Welcome to ', first ='Introduction', mid ='to', last='AI')

def myFun(arg1, arg2, arg3):
  print("arg1:", arg1)
  print("arg2:", arg2)
  print("arg3:", arg3)

# Now we can use *args or **kwargs to
# pass arguments to this function :
args = ("I", "love", "coding.")
myFun(*args)

kwargs = {"arg1" : "Coding", "arg2" : "is", "arg3" : "easy."}
myFun(**kwargs)

def myFun(*args,**kwargs):
  print("args: ", args)
  print("kwargs: ", kwargs)

myFun('I','hate','COVID-19.',first="But",mid="WFH",last="is good.")

"""### **Function 延伸練習**
* 內部函式：你可以在函式內部再定義一個函式。
* 遞迴 Recursion：呼叫自己的函式。
* 匿名函式 lambda function：以一行陳述式來表示。
* ...

### **物件導向 Object-oreinted & Class**
物件概念的開發方式可以提高大型程式的重用性、擴充性和維護性。鼓勵有興趣的同學多多利用網路資源。

# **Numpy**
Numpy 是 Python 的一個重要模組，支援高階大量的維度陣列與矩陣運算，此外也針對陣列運算提供大量的數學函式函式庫。

NumPy的核心功能是ndarray（即n-dimensional array，多維陣列）資料結構。這是一個表示多維度、同質並且固定大小的陣列物件。

To learn more https://numpy.org/doc/stable/reference/arrays.html

## 1.Introduction and Array Creation

### 1.1 Attributes
Numpy 的重點在於陣列的操作，其所有功能特色都建築在同質且多重維度的 `ndarray`，而`ndarray`有三種屬性，分別為維度（ndim）、形狀（shape）和數值類型（dtype）。以下為用來查詢陣列屬性常用的function。

* `ndarray.ndim`
* `ndarray.shape`
* `ndarray.size`
* `ndarry.dtype`
"""

import numpy as np
a = np.array([2, 3, 4])
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print("array a = \n",a)
print("array b = \n",b)
print("--------------")
print("dimenions of a = ",a.ndim)
print("dimenions of b = ",b.ndim)
print("--------------")
print("shape of a = ",a.shape)
print("shape of b = ",b.shape)
print("--------------")
print("datatype of a = ",a.dtype)
print("datatype of b = ",b.dtype)
print("--------------")
print("size of a = ",a.size)
print("size of b = ",b.size)

"""### 1.2 Array Creation
為了能夠快速、有規律地生成陣列，我們可以使用以下function
* `numpy.array`
* `numpy.zeros`
* `numpy.ones`
* `numpy.random.rand`
* `numpy.arange`
* `numpy.linspace`
"""

a = np.array([(1, 2), (3, 4)], dtype=float)
print("array a = \n",a)
print("--------------")
a = np.array([(1, 2), (3, 4)], dtype=complex)
print("array a = \n",a)
print("--------------")
a = np.zeros((3, 4))#by default, the dtype of the created array is float64
print("array a = \n",a)
print("--------------")

a = np.ones((2, 3, 4), dtype=np.int16)
print("array a = \n",a)
print("--------------")
a = np.random.rand(3, 2)#generate numbers between 0 and 1
print("array a = \n",a)
print("--------------")
a = np.arange(6)
print("array a = \n",a)
print("--------------")

a = np.arange(12).reshape(4, 3)
print("array a = \n",a)
print("--------------")
a = np.arange(24).reshape(2, 3, 4)
print("array a = \n",a)
print("--------------")
a = np.arange(0, 2, 0.3)
print("array a = \n",a)
print("--------------")
a = np.linspace(0, 2, 9)
print("array a = \n",a)
print("--------------")

"""## 2.Basic Operations
以下範例為array的一些基本運算，值得注意的是這些運算是單獨對各個元素做運算，而非傳統數學形式上矩陣的運算
"""

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("array a = ",a)
print("array b = ",b)
print("--------------")
print("a - b = ",a - b)
print("--------------")
print("b ** 2 = ",b ** 2)
print("--------------")

print("10 * np.sin(a) = ",10 * np.sin(a))
print("--------------")
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
print("array A = \n",A)
print("array B = \n",B)
print("--------------")
print("A * B = \n",A * B)
print("--------------")
print("A @ B = \n",A @ B)
print("--------------")

"""以下為一些array的function，可以不須使用傳統for loop來進行陣列內資料的處理。
* `ndarray.sum()`
* `ndarray.min()`
* `ndarray.max()`
"""

a = np.random.rand(2, 3)
print("array a = \n",a)
print("--------------")
print("a.sum() = \n",a.sum())
print("--------------")
print("a.min() = \n",a.min())
print("--------------")
print("a.max() = \n",a.max())
print("--------------")

"""以上這些function除了可以對整個陣列做資料處理外，還可以分別對各個axis做處理"""

a = np.arange(12).reshape(3, 4)
print("array a = \n",a)
print("--------------")
print("a.sum(axis=0) = ",a.sum(axis=0))#sum of each column
print("--------------")
print("a.min(axis=1) = ",a.min(axis=1))#min of each row
print("--------------")
print("a.cumsum(axis=0) = \n",a.cumsum(axis=1))#cumulative sum along each ro

"""##3.Indexing, Slicing and Iterating

### 3.1 One-dimensional
利用和python list 中相似的語法，來存取陣列中片段的資料
"""

a = np.arange(10)**3
print("array a = ",a)
print("--------------")
print("a[2] = ",a[2])
print("--------------")
print("a[2:5] = ",a[2:5])
print("--------------")
a[:6:2] = 1000
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
print("array a = ",a)
print("--------------")
print("a[::-1] = ",a[::-1])# reversed a
print("--------------")
for i in a:
    print(i**(1 / 3.))

"""### 3.2 Multidimensional
利用逗號來分隔各個axis上的index，來找尋多維度陣列中的特定元素
"""

def f(x, y):
    return 10 * x + y

a = np.fromfunction(f, (5, 4), dtype=int)
print("array a = \n",a)
print("--------------")
print("a[2, 3] = ",a[2, 3])
print("--------------")
print("a[0:5, 1] = ",a[0:5, 1])# each row in the second column of a
print("--------------")
print("a[:, 1] = ",a[:, 1])# equivalent to the previous example
print("--------------")
print("a[1:3, :] = \n",a[1:3, :])# each column in the second and third row of a
print("--------------")
print("a[-1] = \n",a[-1])# the last row. Equivalent to a[-1, :]

"""##4.Shape Manipulation

### 4.1 Changing the shape of an array
陣列的shape可以透過許多指令來改變，以下列出三中常見的function。
* `ndarray.ravel()`
* `ndarray.reshape()`
* `ndarray.T`

值得注意的是，以上三種function均回傳修改後的陣列，如果要真正修改陣列，需要使用下列function
* `ndarray.resize()`
"""

a = np.floor(10 * np.random.rand(3, 4))
print("array a = \n",a)
print("--------------")
print("a.ravel() = \n",a.ravel())# returns the array, flattened
print("--------------")
print("a.reshape(6, 2) = \n",a.reshape(6, 2))# returns the array with a modified shape
print("--------------")
print("a.T = \n",a.T)# returns the array, transposed
print("--------------")
print("a.T.shape = ",a.T.shape)
print("--------------")
print("a.shape = ",a.shape)
print("--------------")
a.resize((2, 6))
print("array a = \n",a)

"""### 4.2 Stacking together different arrays
透過以下不同function可以沿著不同軸向堆疊陣列
* `numpy.vstack()`
* `numpy.hstack()`

"""

a = np.floor(10 * np.random.rand(2, 2))
b = np.floor(10 * np.random.rand(2, 2))
print("array a = \n",a)
print("--------------")
print("array b = \n",b)
print("--------------")
print("np.vstack((a, b)) = \n",np.vstack((a, b)))
print("--------------")
print("np.hstack((a, b)) = \n",np.hstack((a, b)))
print("--------------")

"""### 4.3 Splitting one array into several smaller ones
可以使用以下的function 來對陣列做縱向切割
* `ndarray.hsplit()`
"""

a = np.floor(10 * np.random.rand(2, 12))
print("array a = \n",a)
print("--------------")
print("np.hsplit(a, 3 = \n",np.hsplit(a, 3))# Split `a` into 3
print("--------------")
print("np.hsplit(a, (3, 4)) = \n",np.hsplit(a, (3, 4)))# Split `a` after the third and the fourth column
print("--------------")

"""# **Pandas**
Pandas是一個Python的package，提供快速、靈活應用的資料結構，讓資料之間的關係變得直觀，成為Python中實用的數據分析工具。

To Learn More : https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html#

## 1. Create a DataFrame
DataFrame可以用來處理結構化的資料，善於處理多維度、欄位的資料，不僅能夠透過Dictionary及Array建立，也能透過讀取外部資料後建立(e.g. csv file)。

### 1.1 Use Dictionary to create a DataFrame
"""

import pandas as pd
grades = {
    "name": ["Duck", "Dog", "Cow", "Cat"],
    "math": [35, 89, 73, 91],
    "chinese": [93, 45, 31, 87]
}
df_dict = pd.DataFrame(grades)
print(df_dict)

"""### 1.2 Use Array to create a DataFrame"""

grades = [ ["Duck", 35, 93], ["Dog", 89, 45],
       ["Cow", 73, 31], ["Cat", 91, 87] ]
df_arr = pd.DataFrame(grades)
print(df_arr)

"""### 1.3 Use CSV file to create a DataFrame"""

# For example, download a csv file online
df_csv = pd.read_csv('http://bit.ly/kaggletrain')
print(df_csv)

"""## 2. DataFrame Operations
以下列出DataFrame的一些基本操作，[更多詳細資料](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)。

### 2.1 `.shape`
* 回傳df列數與欄數
"""

print(df_dict.shape)
print(df_arr.shape)
print(df_csv.shape)

"""### 2.2 `.index/ .columns`
* 可以改變及回傳index、columns的名稱
"""

grades = [ ["Duck", 35, 93], ["Dog", 89, 45],
       ["Cow", 73, 31], ["Cat", 91, 87] ]
df_arr = pd.DataFrame(grades)
print(df_arr)
print(df_arr.index)
print(df_arr.columns)
print("----")

# Add label (index and columns)
df_arr.index = ["student1", "student2", "student3", "student4"]
df_arr.columns = ["name", "math", "chinese"]
print(df_arr)
print(df_arr.index)
print(df_arr.columns)

"""### 2.3 `.head()/ .tail()`
* df.head(n) 能夠回傳前n筆資料
* df.tail(n) 能夠回傳後n筆資料
"""

print(df_dict.head(2))
print(df_dict.tail(2))
print("----")

print(df_csv.head(5))
print(df_csv.tail(5))

"""### 2.4 `.describe()`
* 生成描述性統計數據，總結數據集分佈的集中趨勢，分散和形狀。
"""

# Example 1
df = pd.DataFrame({'categorical': pd.Categorical(['d','e','f']),
                   'numeric': [1, 2, 3],
                   'object': ['a', 'b', 'c']
                  })
# Only return numeric fields
print(df.describe()) # OR print(df.describe(include=[np.number]))

# Describing all columns of a DataFrame regardless of data type.
print(df.describe(include='all'))

print("----")

# Example 2
print(df_csv.describe())

"""### 2.5 `.info()`
* 進行數據分析時為了快速瀏覽dataset，常會使用.info()來獲取DataFrame的簡要摘要(e.g. 檢視索引、資料型態和記憶體資訊)。
"""

print(df_csv.info())

"""### 2.6 `[]/ .at[]/ .iat[]`
* 在中括號輸入指定的「欄位名稱」或「資料索引值」，來獲取需要的資料集
* df[col]: 以Series形式回傳單一欄位資料
* df[[col]]: 以DataFrame形式回傳單一欄位資料
* df[[col1, col2]]: 以DataFrame形式回傳多個欄位資料
* df[i:j]: 取得索引值i:j-1的資料

* df.at[index, "col_name"]: 取得指定index/欄位名稱的單一值
* df.iat[index, col]: 取得指定index/column的單一值
"""

# Example []
print(df_dict["name"])
print("----")
print(df_dict[["name"]])
print("----")
print(df_dict[["math","chinese"]])
print("----")
print(df_dict[0:2])
print("----")

# Example .at[]
print(df_dict)
print("----")
print(df_dict.at[3,"math"])
print("----")

# Example .iat[]
print(df_dict.iat[3,1])

"""### 2.7 `.loc`
* .loc: 利用行標籤和列標籤（x_label、y_label）進行索引
"""

print(df_dict)
print("----")
print(df_dict.loc[3,'math'])
print("----")
print(df_dict.loc[0:2,:])
print("----")
print(df_dict.loc[:,'math':'chinese'])
print("----")
print(df_dict.loc[0:1,'name':'math'])
print("----")
print(df_dict.loc[[0,2],['name','chinese']])

"""### 2.8 `.iloc`
* .iloc: 利用行索引和列索引（index，columns）查找資料且都是從0開始
* 適用於label較長的資料集
"""

print(df_dict)
print("----")
print(df_dict.iloc[3,1])
print("----")
print(df_dict.iloc[0:2,:])
print("----")
print(df_dict.iloc[:,0:2])
print("----")
print(df_dict.iloc[0:2,0:2])
print("----")
print(df_dict.iloc[[0,2],[0,2]])

"""## 3. Saving the DataFrame
在處理完數據集後，我們需要將處理後的數據保存為某種檔案格式，(e.g csv、excel)或其它格式。
"""

df_dict.to_csv('data.csv', index=False)
# OR df_dict.to_excel('data.xls', index=False)

"""# 其他常用套件：


*   [matplotlib](https://matplotlib.org/stable/gallery/index.html) : Visualization with Python
*   [scipy](https://scipy.org/getting-started.html) : Scientific Computing Tools for Python
*   [scikit-learn](https://scikit-learn.org/stable/user_guide.html) : Machine Learning in Python

## **Homework**

### **(1) A Phone Book**
Write a problem that allows user to store and search contact information.
Each entry of the contact information should contain the `name` and `phone`. As an example using `dict`, it would look like

`
{
  "name": "John",
  "phone": "0987-654321,
}
`
<br/><br/>
You may use a `list` of `dict` as data structure of the phone book, or if you prefer, any other suitable data container to implement the phone book.
As an example using `list` of `dict`, it would look like

`
[{
  "name": "John",
  "phone": "0987-654321,
}, {
  "name": "Andrew",
  "phone": "0912-343531,
}, {
  "name": "Catherine",
  "phone": "0956-396471,
}, ... ]
`
<br/><br/>
**Requirements**
1. Implement a function `add(name, phone)` which allows user to add an entry to the phone book.
1. Implement a function `find(name="", phone="")` which allows user to search the phone book ***either*** by "name" or "phone".
1. Implement a function `print_all()` which allows user to print the phone book. For each line, print one entry in the format of `"name / phone number"`.
"""



"""### **(2) Find a missing number from a list**
Use a function and write a python program to find a missing number from a list.

Ex. `Input: [1, 2, 3, 5, 6, 7]`, `Output: 4`

"""



"""### **(3) Reverse a string**

Write a function to reverse a string.

Sample String : "abcd4567"

Expected Output : "7654dcba"
"""
str = ["a","b","c","d",4,5,6,7]
print("str[::-1] = ",str[::-1])


"""### **(4) Calculate the harmonic sum**
Harmonic series is inverse of a arithmetic progression. In general, the terms in a harmonic progression can be denoted as 1/a, 1/(a + d), 1/(a + 2d), 1/(a + 3d) …. 1/(a + nd).
As Nth term of AP is given as ( a + (n – 1)d). Hence, Nth term of harmonic progression is reciprocal of Nth term of AP, which is 1/(a + (n – 1)d), where “a” is the 1st term of AP and “d” is a common difference.

Example:

![CodeCogsEqn.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALcAAAAlBAMAAADy7mXkAAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMARM0yInYQiatmmbtU3e/6iv2wAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAB5UlEQVRIDe2WPywDYRjGH3qOI1rMBmFglHSwcYvE2DCIhZvYkPhbBkJwEYkaGgkLE9FYxGTqbGSzWAwm8SeREEkdd9d63q+nHdqtt3zf83vf57nLm7uvBeRV1SFJS7cgClA9wuFJbehNFPr7RLgCVI+IyEkZjogIVwEUTy6Od0pjJfxnQJWx8GviqbKO5UXeMtIkiAKgeITDk/ri6wxXJnY7+StSgOrxE5SDwi+UYM0eFJYM0wsCFPT4H/eezDLkqBWAgp5K+O9U5eTKP5Z622637Wnn7hnnenbWU3uty95yNpEfkg/843Ha3av8T+7cp+BrBTnQIjz+QVHK8AFL28SAhexBUcrwXjP0gF7TG3y5xuLHj3ub4VTa3emWuxrJDQZAjwvgebTO5KVs8Tp4qTX1DyZxRGJMcMdau380mQSoxm6cc2kZ4VUmxjZrLc06UIUTWJHFqQST6BnrosMd2wVbgUEBEjJ8ZL9JtARJTf5CHxxxqwERrsdwyy2BqloMATi0qDkqw51qijqCRVwpNbQRSuQJH6WOQGHIB19H/fvfbuNk4Yb/IDSmMfa3I3jfCoOK2hfqnokAV6yrzSLHEjpuvmbrPCZjTGS4YekPoiO/DGcyn1ypmdthgJ6nWSbJJZOBq74BU4+MGZhA8tsAAAAASUVORK5CYII=)

Write a function to calculate the harmonic sum of n-1.

"""

